# Generated by Django 2.0.2 on 2024-05-01 04:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(blank=True, max_length=100, null=True)),
                ('category_state', models.CharField(blank=True, default='Activa', max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categorys',
                'ordering': ['producto__stock_producto'],
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_producto', models.CharField(blank=True, max_length=100, null=True)),
                ('precio_producto', models.IntegerField(blank=True, null=True)),
                ('stock_producto', models.IntegerField(blank=True, null=True)),
                ('stock_minimo_producto', models.IntegerField(blank=True, null=True)),
                ('stock_maximo_producto', models.IntegerField(blank=True, null=True)),
                ('descripcion_producto', models.CharField(blank=True, max_length=100, null=True)),
                ('imagen_producto', models.CharField(blank=True, max_length=240, null=True)),
                ('estado_producto', models.CharField(blank=True, default='No', max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['stock_producto'],
            },
        ),
        migrations.AddField(
            model_name='category',
            name='producto',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='inventario.Producto'),
        ),
    ]
