# Generated by Django 2.0.2 on 2024-05-01 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_auto_20240501_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='estado_producto',
            field=models.CharField(blank=True, default='medio', max_length=100, null=True),
        ),
    ]
