# Generated by Django 2.0.2 on 2024-05-02 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_auto_20240501_1232'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category_group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_group_name', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Category_group',
                'verbose_name_plural': 'Category_groups',
                'ordering': ['category_group_name'],
            },
        ),
        migrations.AddField(
            model_name='category',
            name='category_group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='inventario.Category_group'),
        ),
    ]
