# Generated by Django 2.0.2 on 2024-05-07 06:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0006_auto_20240506_1949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_group',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='inventario.Category_group'),
        ),
    ]
