# Generated by Django 2.0.2 on 2024-05-13 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0007_auto_20240507_0238'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='codigo_producto',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
