# Generated by Django 2.0.2 on 2024-06-02 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0009_auto_20240513_1929'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='category_state',
        ),
        migrations.AddField(
            model_name='category_group',
            name='category_state',
            field=models.CharField(blank=True, default='Activa', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='producto_estado',
            field=models.CharField(blank=True, default='Activo', max_length=100, null=True),
        ),
    ]
