# Generated by Django 2.0.2 on 2024-06-02 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0010_auto_20240601_2246'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='producto_state',
            field=models.CharField(blank=True, default='Activa', max_length=100, null=True),
        ),
    ]
