# Generated by Django 2.0.2 on 2024-06-07 02:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0011_producto_producto_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='producto_estado',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='producto_state',
        ),
    ]
