# Generated by Django 2.0.2 on 2024-06-07 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0011_producto_producto_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='producto_estado',
        ),
        migrations.AlterField(
            model_name='producto',
            name='imagen_producto',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
