# Generated by Django 2.0.2 on 2024-06-09 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0012_auto_20240607_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='producto_estado',
            field=models.CharField(blank=True, default='Activo', max_length=100, null=True),
        ),
    ]
