# Generated by Django 2.0.2 on 2024-06-09 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0013_producto_producto_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='producto_state',
            field=models.CharField(blank=True, default='Activa', max_length=100, null=True),
        ),
    ]
