# Generated by Django 2.0.2 on 2024-06-09 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0013_auto_20240608_1938'),
        ('inventario', '0013_auto_20240607_1256'),
    ]

    operations = [
    ]
