# Generated by Django 2.0.2 on 2024-06-09 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0014_merge_20240609_0144'),
        ('inventario', '0014_merge_20240609_0510'),
    ]

    operations = [
    ]
