# Generated by Django 2.0.2 on 2024-05-16 22:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventario', '0009_auto_20240513_1929'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_calle', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Calle',
                'verbose_name_plural': 'Calles',
                'ordering': ['nombre_calle'],
            },
        ),
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_comuna', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Comuna',
                'verbose_name_plural': 'Comunas',
                'ordering': ['nombre_comuna'],
            },
        ),
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_dirrecion', models.CharField(blank=True, max_length=100, null=True)),
                ('calle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proveedor.Calle')),
            ],
            options={
                'verbose_name': 'Direccion',
                'verbose_name_plural': 'Direcciones',
                'ordering': ['numero_dirrecion'],
            },
        ),
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_orden', models.IntegerField()),
                ('direccion_orden', models.CharField(max_length=100)),
                ('telefono_orden', models.IntegerField(blank=True, null=True)),
                ('estado_orden', models.CharField(blank=True, default='t', max_length=100, null=True)),
                ('descuento', models.FloatField(blank=True, null=True)),
                ('tasa', models.FloatField(blank=True, null=True)),
                ('total_impuesto', models.FloatField(blank=True, null=True)),
                ('total_compra', models.FloatField(blank=True, null=True)),
                ('creacion', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Orden',
                'verbose_name_plural': 'Ordenes',
                'ordering': ['numero_orden'],
            },
        ),
        migrations.CreateModel(
            name='OrdenProducto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_producto', models.IntegerField(blank=True, null=True)),
                ('precio_producto', models.IntegerField(blank=True, null=True)),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proveedor.Orden')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.Producto')),
            ],
            options={
                'verbose_name': 'OrdenProducto',
                'verbose_name_plural': 'OrdenProductos',
                'ordering': ['cantidad_producto'],
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_proveedor', models.CharField(blank=True, max_length=100, null=True)),
                ('correo_proveedor', models.CharField(blank=True, max_length=100, null=True)),
                ('telefono_proveedor', models.IntegerField(blank=True, null=True)),
                ('estado_proveedor', models.CharField(blank=True, default='t', max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
                'ordering': ['nombre_proveedor'],
            },
        ),
        migrations.CreateModel(
            name='ProveedorDireccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departamento', models.CharField(blank=True, max_length=100, null=True)),
                ('piso', models.CharField(blank=True, max_length=100, null=True)),
                ('direccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proveedor.Direccion')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proveedor.Proveedor')),
            ],
            options={
                'verbose_name': 'ProveedorDireccion',
                'verbose_name_plural': 'ProveedorDirecciones',
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_region', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Region',
                'verbose_name_plural': 'Regiones',
                'ordering': ['nombre_region'],
            },
        ),
        migrations.AddField(
            model_name='comuna',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proveedor.Region'),
        ),
        migrations.AddField(
            model_name='calle',
            name='comuna',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proveedor.Comuna'),
        ),
    ]
