# Generated by Django 2.0.2 on 2024-05-23 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedor', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='direccion',
            options={'ordering': ['numero_direccion'], 'verbose_name': 'Direccion', 'verbose_name_plural': 'Direcciones'},
        ),
        migrations.RemoveField(
            model_name='direccion',
            name='numero_dirrecion',
        ),
        migrations.AddField(
            model_name='direccion',
            name='numero_direccion',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='direccion',
            name='departamento',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='direccion',
            name='nombre_calle',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='direccion',
            name='piso',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
