# Generated by Django 2.0.2 on 2024-05-21 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='direccion',
            name='numero_dirrecion',
            field=models.IntegerField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='proveedordireccion',
            name='departamento',
            field=models.IntegerField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='proveedordireccion',
            name='piso',
            field=models.IntegerField(blank=True, max_length=100, null=True),
        ),
    ]
