# Generated by Django 2.0.2 on 2024-05-21 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedor', '0002_auto_20240520_2358'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proveedordireccion',
            options={'ordering': ['proveedor'], 'verbose_name': 'ProveedorDireccion', 'verbose_name_plural': 'ProveedorDirecciones'},
        ),
        migrations.AlterField(
            model_name='direccion',
            name='numero_dirrecion',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='proveedordireccion',
            name='departamento',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='proveedordireccion',
            name='piso',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
