# Generated by Django 2.0.2 on 2024-05-28 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedor', '0002_auto_20240523_1936'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ordenproducto',
            options={},
        ),
        migrations.AddField(
            model_name='ordenproducto',
            name='nombre_producto',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
