# Generated by Django 2.0.2 on 2024-05-28 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proveedor', '0003_auto_20240528_0426'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ordenproducto',
            options={'ordering': ['cantidad_producto'], 'verbose_name': 'OrdenProducto', 'verbose_name_plural': 'OrdenProductos'},
        ),
    ]
