# Generated by Django 2.0.2 on 2024-05-21 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedor', '0003_auto_20240521_1700'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor',
            name='rut_proveedor',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
