# Generated by Django 2.0.2 on 2024-05-28 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedor', '0004_auto_20240528_0437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordenproducto',
            name='nombre_producto',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ordenproducto',
            name='precio_producto',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
