# Generated by Django 2.0.2 on 2024-06-03 22:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proveedor', '0005_auto_20240528_0457'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='proveedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='proveedor.Proveedor'),
        ),
    ]
