# Generated by Django 2.0.2 on 2024-06-03 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedor', '0006_orden_proveedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='formatted_numero_orden',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
