# Generated by Django 2.0.2 on 2024-06-03 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedor', '0007_orden_formatted_numero_orden'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='nota_orden',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
