# Generated by Django 2.0.2 on 2024-06-09 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedor', '0008_orden_nota_orden'),
    ]

    operations = [
        migrations.AlterField(
            model_name='direccion',
            name='departamento',
            field=models.CharField(blank=True, default=0, max_length=100, null=True),
        ),
    ]
