# Generated by Django 2.0.2 on 2024-04-29 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='horas_trabajadas',
            field=models.FloatField(default=0),
        ),
    ]
