# Generated by Django 2.0.2 on 2024-05-25 23:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventario', '0009_auto_20240513_1929'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut_cliente', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('nombre_cliente', models.CharField(blank=True, max_length=100, null=True)),
                ('apellido_cliente', models.CharField(blank=True, max_length=100, null=True)),
                ('correo_cliente', models.CharField(blank=True, max_length=100, null=True)),
                ('telefono_cliente', models.IntegerField(blank=True, null=True)),
                ('estado_cliente', models.CharField(blank=True, default='t', max_length=100, null=True)),
                ('creacion_cliente', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Creación')),
                ('actualizacion_cliente', models.DateTimeField(auto_now=True, verbose_name='Fecha Actualización')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['nombre_cliente'],
            },
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_pago', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
                'ordering': ['nombre_pago'],
            },
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creacion_venta', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Creación')),
                ('total_venta', models.IntegerField()),
                ('codigo_venta', models.IntegerField(editable=False, unique=True)),
                ('formatted_codigo_venta', models.CharField(blank=True, max_length=20)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='venta.Cliente')),
                ('pago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='venta.Pago')),
            ],
            options={
                'verbose_name': 'Venta',
                'verbose_name_plural': 'Ventas',
                'ordering': ['formatted_codigo_venta'],
            },
        ),
        migrations.CreateModel(
            name='VentaProducto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.Producto')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='venta.Venta')),
            ],
            options={
                'verbose_name': 'VentaProducto',
                'verbose_name_plural': 'VentaProductos',
                'ordering': ['venta'],
            },
        ),
    ]
