# Generated by Django 2.0.2 on 2024-05-27 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventaproducto',
            name='cantidad',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
