# Generated by Django 2.0.2 on 2024-05-27 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0002_ventaproducto_cantidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventaproducto',
            name='precio_total',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ventaproducto',
            name='precio_unitario',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
